export const C = {
  PORT: 'PORT',
  NODE_ENV: 'NODE_ENV',
  MONGODB_CONNECTION_STRING: 'MONGODB_CONNECTION_STRING',
  HOST: 'HOST',
  LOG_LEVEL: 'LOG_LEVEL',
  LOG_NAMESPACES: 'LOG_NAMESPACES',
  APP_NAME: 'APP_NAME',
  NO_LOGS: 'NO_LOGS',
};

export const ERROR_CODES = {
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
};
